config/routes.rb
Rails.application.routes.draw do
  resources :posts
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  validates :title, presence: true
  validates :start_at, presence: true
  validates :end_at, presence: true
  validates :memo, length: {maximum: 500}
  validate :start_end_check
  def start_end_check
    errors.add(:end_at, "は今日以降の日付で選択してください。") unless
    :start_at > :end_at 
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts = Post.all.order(created_at: :desc)
  end
  
  def new
    @post = Post.new
  end
  
  def show
    @post = Post.find(params[:id])
  end

  def edit
    @post = Post.find(params[:id])
  end  
    
  def create
    @post = Post.new(post_params)
    if @post.save
      flash[:success] = "投稿を作成しました"
      redirect_to :posts
    else
      flash[:failure] = "投稿を作成できませんでした"
      render :new
    end
  end
  
  def update
    @post = Post.find(params[:id])
    if @post.update(post_params)
      flash[:success] = "投稿を更新しました"
      redirect_to :posts
    else
      flash[:failure] = "投稿を更新できませんでした"
      render :edit
    end
  end
  
  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    flash[:success] = "投稿を削除しました"
    redirect_to :posts
  end
  
  private
  
  def post_params
    params.require(:post).permit(
    :title,
    :start_at,
    :end_at,
    :is_all_day,  
    :memo  
    )
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TaskApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <h1>Ruby on Rails スケジュール管理アプリ</h1>
    </header>
    
    <footer>
      <h1>現在の日時: <%= Date.current.strftime("%Y年%m月%d日") %></h1>
    </footer>
    <%= yield %>
  </body>
</html>

app/views/layouts/shared/_error.html.erb
<% if obj.errors.any? %>
    <% obj.errors.full_messages.each do |message| %>
      <ul>
        <li><%= message %></li>
      </ul>
    <% end %>
<% end %>

app/views/posts/edit.html.erb
<div class="main_container">
  <div class="infomation">
    <h2>スケジュール一覧</h2>
    <%= render 'layouts/shared/error', obj: @post %>
    <% if flash[:failure] %>
      <p class="failure">
        <%= flash[:failure] %>
      </p>
    <% end %>
  </div>
  <%= form_tag(post_path, {method: :put}) do %>
    <table>
      <tbody>
        <tr>
          <th>
            <label for="post_title">タイトル</label>
          </th>
          <td>
            <input type="text" name="post[title]" id="post_title" value="<%= @post.title %>">
          </td>
        </tr>
        <tr>
          <th>
            <label for="post_start_at">開始日</label>
          </th>
          <td>
            <input value="<%= @post.start_at.to_date %>" type="date" name="post[start_at]" id="post_start_at">
          </td>
        </tr>
        <tr>
          <th>
            <label for="post_end_at">終了日</label>
          </th>
          <td>
            <input value="<%= @post.end_at.to_date %>" type="date" name="post[end_at]" id="post_end_at">
          </td>
        </tr>
        <tr>
          <th>
            <label for="post_is_all_day">終日</label>
          </th>
          <td>
            <input name="post[is_all_day]" type="hidden" value="0">
            <input type="checkbox" name="post[is_all_day]" id="post_is_all_day" value="<%= @post.is_all_day %>" <%= "checked='checked'" if @post.is_all_day %>>
            終日の場合はチェックを入れます
          </td>
        </tr>
        <tr>
          <th>
            <label for="post_memo">スケジュールメモ</label>
          </th>
          <td>
            <textarea class="posts-content" name="post[memo]" id="post_memo"><%= @post.memo %></textarea>
          </td>
        </tr>
      </tbody>
    </table>
    <div>
      <ul>
        <li>
          <input type="submit" name="commit" value="スケジュールの編集を完了する" data-disable-with="スケジュールの編集を完了する">
        </li>
        <li>
          <%= link_to("スケジュール一覧に戻る", "/posts") %>
        </li>
      </ul>
    </div>
  <% end %>
</div>

app/views/posts/index.html.erb
<h2>スケジュール一覧</h2>
<% if flash[:success] %>
  <p class="success">
    <%= flash[:success] %>
  </p>
<% elsif flash[:failure] %>
  <p class="failure">
    <%= flash[:failure] %>
  </p>
<% end %>
<table>
  <thead>
     <tr>
      <th>ID</th>
      <th>タイトル</th>
      <th>開始日</th>
      <th>終了日</th>
      <th>終日</th>
      <th>スケジュール更新日時</th>
      <th>確認</th>
      <th>編集</th>
      <th>削除</th>
      </tr>
  </thead>
  <tbody>
     <% if @posts.count > 0 %>
      <% @posts.each do |post| %>
        <tr>
          <td>
            <%= post.id %>
          </td>
            
          <td>
            <%= post.title %>
          </td>
            
          <td>
            <%= post.start_at.strftime("%Y年%m月%d日") %>
          </td>
            
          <td>
            <%= post.end_at.strftime("%Y年%m月%d日") %>
          </td>
            
          <td>
            <% if post.is_all_day %>
              <string>o</string>
            <% end %>
          </td>
            
          <td>
            <%= post.updated_at.strftime("%Y年%m月%d日%H時%M分") %>            
          </td>
            
          <td>
            <%= link_to "確認", post_path(post) %>
          </td>
            
          <td>
            <%= link_to "編集", edit_post_path(post) %>
          </td>
            
          <td>
            <%= link_to "削除", post_path(post), method: :delete , data: {confirm: "本当に削除しますか？"} %>
          </td>
        </tr>
      <% end %>
    <% else %>
      <td colspan= "9">現在登録しているスケジュールはありません</td>
    <% end %>
  </tbody>
</table>

<p>
  <%= link_to("スケジュール新規登録", "/posts/new") %>
</p>

<footer>
   <h1>現在の日時: <%= Date.current.strftime("%Y年%m月%d日") %>  スケジュール合計:<%= @posts.all.count %></h1>
</footer>

app/views/posts/new.html.erb
<div class="main-container">
  <div class="infomation">
    <h2>スケジュール一覧</h2>　
    <%= render 'layouts/shared/error', obj: @post %>
    <% if flash[:failure] %>
      <p class="failure"><%= flash[:failure] %></p>
    <% end %>
  </div>
  <%= form_tag(posts_path, {method: :post}) do %>
    <table>
      <tbody>
        <tr>
          <th>
            <label for="post_title">タイトル</label>
          </th>
          <td>
            <input type="text" name="post[title]" value="<%= @post.title %>">
          </td>
        </tr>
        <tr>
          <th>
            <label for="post_start_at">開始日</label>
          </th>
          <td>
            <input type="date" name="post[start_at]" value="<%= @post.start_at %>">
          </td>
        </tr>
        <tr>
          <th>
            <label for="post_end_at">終了日</label>
          </th>
          <td>
            <input type="date" name="post[end_at]" value="<%= @post.end_at %>">
          </td>
        </tr>
        <tr>
          <th>
            <label for="post_is_all_day">終日</label>
          </th>
          <td>
            <input name="post[is_all_day]" type="hidden" value="0">
            <input type="checkbox" name="post[is_all_day]" id="post_is_all_day">
            終日の場合はチェックを入れます
          </td>
        </tr>
        <tr>
          <th>
            <label for="post_memo">スケジュールメモ</label>
          </th>
          <td>
            <textarea class="posts-content" name="post[memo]"><%= @post.memo %></textarea>
          </td>
        </tr>
      </tbody>
    </table>
    <div>
      <ul>
        <li>
          <input type="submit" name="commit" value="スケジュールを新規登録する" data-disable-with="スケジュールを新規登録する">
        </li>
        <li>
          <%= link_to "スケジュール一覧に戻る", :posts %>
        </li>
      </ul>
    </div>
  <% end %>
</div>

app/views/posts/show.html.erb
<div class="main_container">
  <div class="information">
    <h2>スケジュール詳細</h2>
  </div>
  <table> 
    <tbody>
      <tr>
        <th>タイトル</th>
        <td>
          <%= @post.title %>
        </td>
        </tr>
      <tr>
        <th>開始日</th>
        <td>
          <%= @post.start_at.strftime("%Y年%m月%d日") %>
        </td>
      </tr>
      <tr>
        <th>投稿日時</th>
        <td>
          <%= @post.created_at.strftime("%Y年%m月%d日") %>
        </td>
      </tr>
      <tr>
        <th>終日</th>
        <td>
          <% if @post.is_all_day %>
            <strong>○</strong>
          <% end%>
        </td>
      </tr>
      <tr>
        <th>スケジュールメモ</th>
        <td>
          <pre>
            <%= @post.memo %>
          </pre>
        </td>
      </tr>
    </tbody>
  </table>

  <ul>
    <li>
      <%= link_to "スケジュール一覧に戻る", :posts %>
    </li>
    <li>
      <%= link_to "スケジュールを編集する", :edit_post %>
    </li>
    <li>
      <%= link_to "削除", post_path(@post), method: :delete , data: {confirm: "本当に削除しますか？"} %>
    </li>
  </ul>
</div>